use std::collections::HashMap;
use std::path::PathBuf;

// Generated by build.rs — defines get_embedded_rule_sets()
include!(concat!(env!("OUT_DIR"), "/rule_sets_data.rs"));

/// Get the rule-sets cache directory
pub fn rule_sets_dir() -> PathBuf {
    let home = std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .unwrap_or_else(|_| ".".to_string());
    let mut path = PathBuf::from(home);
    path.push(".local");
    path.push("share");
    path.push("aurorabox");
    path.push("rulesets");
    path
}

/// Extract all embedded rule-sets to the cache directory.
/// Returns a map of tag → local file:// URL.
pub fn extract_rule_sets() -> HashMap<String, String> {
    let dir = rule_sets_dir();
    std::fs::create_dir_all(&dir).ok();

    let mut paths = HashMap::new();
    let embedded = get_embedded_rule_sets();

    for (tag, data) in embedded {
        if data.len() < 50 {
            continue;
        }

        let filename = format!("{}.srs", tag);
        let dest = dir.join(&filename);
        if !dest.exists() {
            if let Err(e) = std::fs::write(&dest, data) {
                log::warn!("Failed to extract rule-set {}: {}", tag, e);
                continue;
            }
            log::info!(
                "Extracted rule-set: {} ({:.1} KB)",
                tag,
                data.len() as f64 / 1024.0
            );
        }

        let local_path = dest.display().to_string();
        paths.insert(tag.to_string(), local_path);
    }

    paths
}

/// Get the list of available rule-set tags from embedded data
pub fn available_tags() -> Vec<String> {
    get_embedded_rule_sets()
        .into_iter()
        .filter(|(_, d)| d.len() > 500)
        .map(|(t, _)| t.to_string())
        .collect()
}
